#! /usr/bin/env ruby

require 'pg'

db = PG.connect(dbname: 'expenses')

def list_expenses(db)
  result = db.exec('SELECT * FROM expenses ORDER BY created_on DESC;')

  result.each do |row|
    columns = [ row["id"].rjust(3),
                row["created_on"].rjust(10),
                row["amount"].rjust(12),
                row["memo"] ]

    puts columns.join(" | ")
  end
end

def display_help
  puts %(
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  )
end

case ARGV.first
 when 'list'
   list_expenses(db)
 else
   display_help
end
